[project]
authors = ["Ryan Oates <ryanoatsie@outlook.com>"]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
name = "scripts"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
openai = ">=1.82.1,<2"
anthropic = ">=0.52.1,<0.53"
pip = ">=25.1.1,<26"
